### ISSUE TITLE
DESCRIPTION

### ISSUE THREAD

**Issue by Nowosad** [Graczykowski/twiGPS#7]
1. `Title:` -- the title should be shorter and only use capital letters
2. `Description:` -- it should be more about the methods/tools, and not about example data. You should also include some references, see e.g., see https://github.com/Nowosad/supercells/blob/master/DESCRIPTION --
3. `Authors` -- only use the fields you can fill (i.e., first name, surname and email)

**Comment by Graczykowski** [comment]
Added in version 0.1.2
