### ISSUE TITLE
R crash

### ISSUE THREAD

**Issue by Nowosad** [Graczykowski/twiGPS#9]
The example below crashes my R session:

```r
devtools::load_all()
geolife_vect = terra::vect(geolife_sandiego,
                           geom = c("lon", "lat"),
                           crs = "EPSG:4326") |>
  terra::project("EPSG:32611")
# activity space for data.frame 'data'
exposure_PO(data = geolife_vect, cellsize = 50,
            normalize = "range", group_split = date)
```

**Comment by Nowosad** [comment]
Same with:

```
exposure_DR(data = geolife_vect, bandwidth = 200,
   cellsize = 50, normalize = "range", group_split = date)
```

**Comment by Nowosad** [comment]
The problem can be reproduced: https://github.com/Graczykowski/twiGPS/actions/runs/9285743627/job/25550945650

**Comment by Graczykowski** [comment]
Error introduced in new version of terra (1.7-78)  - until the bug is fixed package will require terra version 1.7-65 or older which works correctly

**Comment by Nowosad** [comment]
@Graczykowski is this bug already reported by someone else at the terra GitHub issue? If not -- please try to isolate the error (*reprex*) and report it. In general, R packages should not require old versions of the packages.

**Comment by Graczykowski** [comment]
bug reported in https://github.com/rspatial/terra/issues/1530

**Comment by Graczykowski** [comment]
Issue closed with terra fix
